language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm install
  - npm run docs:build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: docs/.vuepress/dist
on:
  branch: master