language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm install
  # - "./deploy.sh"
  - npm run docs:build
  - cd docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  # - git push -f git@github.com:justbefree/youdefine-docs.git master:gh-pages
  # https://github.com/justbefree/youdefine-docs.git
  - git push -f https://${GITHUB_TOKEN}@github.com/justbefree/docs.git master:gh-pages
  - npm run update:info

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: docs/.vuepress/dist
on:
  branch: master